inherit_from: .rubocop_todo.yml

AllCops:
  # Exclude:
  #   - 'vendor/**/*'
  DefaultFormatter: progress
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  # TargetRubyVersion: 2.3

Metrics/LineLength:
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https
